import { textbookPackage as yuwen2bPackage } from "./renjiao-yuwen-2b";

const yuwen3aLessons = [
  ["1", "大青树下的小学"],
  ["2", "花的学校"],
  ["3", "不懂就要问"],
  ["4", "古诗三首"],
  ["5", "铺满金色巴掌的水泥道"],
  ["6", "秋天的雨"],
  ["7", "听听，秋的声音"],
  ["8", "去年的树"],
  ["9", "那一定会很好"],
  ["10", "在牛肚子里旅行"],
  ["11", "一块奶酪"],
  ["12", "总也倒不了的老屋"],
  ["13", "胡萝卜先生的长胡子"],
  ["14", "小狗学叫"],
  ["15", "搭船的鸟"],
  ["16", "金色的草地"],
  ["17", "古诗三首"],
  ["18", "富饶的西沙群岛"],
  ["19", "海滨小城"],
  ["20", "美丽的小兴安岭"],
  ["21", "大自然的声音"],
  ["22", "读不完的大书"],
  ["23", "父亲、树林和鸟"],
  ["24", "司马光"],
  ["25", "灰雀"],
  ["26", "手术台就是阵地"],
  ["27", "一个粗瓷大碗"],
].map(([lessonNo, title], index) => ({
  id: `lesson_3a_${lessonNo}`,
  unit: `三年级上册·第${Math.floor(index / 3) + 1}组`,
  lessonNo,
  title,
  shortTitle: `第${lessonNo}课《${title}》`,
  page: index + 1,
  recognitionChars: [],
  writingChars: [],
  words: [title],
  readingText: `请朗读《${title}》中老师布置的一个自然段。`,
  contentStatus: "目录已接入，生字词待结构化",
}));

const math2bLessons = [
  "数据收集整理",
  "表内除法（一）",
  "图形的运动（一）",
  "表内除法（二）",
  "混合运算",
  "有余数的除法",
  "万以内数的认识",
  "克和千克",
  "数学广角-推理",
  "总复习",
].map((title, index) => ({
  id: `math_2b_${index + 1}`,
  unit: "数学二年级下册",
  lessonNo: `${index + 1}`,
  title,
  shortTitle: `第${index + 1}单元《${title}》`,
  page: index + 1,
  writingChars: [],
  words: [title],
  readingText: `请说一说《${title}》这一单元今天复习的知识点。`,
  contentStatus: "教材目录已接入，题型待按数学专项结构化",
}));

const math3aLessons = [
  "时、分、秒",
  "万以内的加法和减法（一）",
  "测量",
  "万以内的加法和减法（二）",
  "倍的认识",
  "多位数乘一位数",
  "长方形和正方形",
  "分数的初步认识",
  "数学广角-集合",
  "总复习",
].map((title, index) => ({
  id: `math_3a_${index + 1}`,
  unit: "数学三年级上册",
  lessonNo: `${index + 1}`,
  title,
  shortTitle: `第${index + 1}单元《${title}》`,
  page: index + 1,
  writingChars: [],
  words: [title],
  readingText: `请说一说《${title}》这一单元今天复习的知识点。`,
  contentStatus: "教材目录已接入，题型待按数学专项结构化",
}));

export const textbookPackages = [
  {
    ...yuwen2bPackage,
    contentStatus: "已结构化：课次、写字表、词语表、部分拼音和朗读段落",
  },
  {
    id: "rj-yuwen-3a-2026",
    name: "人教版/统编版 语文 三年级上册",
    subject: "语文",
    grade: "三年级",
    semester: "上册",
    version: "人教版/统编版",
    sourceFile: "教材/人教版 语文 三年级 上册.pdf",
    extractionNote: "已接入教材目录骨架；生字、词语、拼音、课文段落后续继续结构化。",
    contentStatus: "目录已接入，生字词待结构化",
    lessons: yuwen3aLessons,
  },
  {
    id: "rj-math-2b-2026",
    name: "人教版 数学 二年级下册",
    subject: "数学",
    grade: "二年级",
    semester: "下册",
    version: "人教版",
    sourceFile: "教材/人教版 数学  二年级下册.pdf",
    extractionNote: "已接入教材单元目录骨架；数学题型后续按口算、应用题、单位、图形专项结构化。",
    contentStatus: "目录已接入，数学专项题型待结构化",
    lessons: math2bLessons,
  },
  {
    id: "rj-math-3a-2026",
    name: "人教版 数学 三年级上册",
    subject: "数学",
    grade: "三年级",
    semester: "上册",
    version: "人教版",
    sourceFile: "教材/人教版 数学 三年级 上册.pdf",
    extractionNote: "已接入教材单元目录骨架；数学题型后续按口算、应用题、单位、图形专项结构化。",
    contentStatus: "目录已接入，数学专项题型待结构化",
    lessons: math3aLessons,
  },
];

export const defaultTextbookPackage = textbookPackages[0];
